# Site settings
title: It's Only the Future if We Develop
header-img: img/home-bg.png
email: alfredo.i.urdaneta@gmail.com
copyright_name: aurda012
description: > # this means to ignore newlines until "baseurl:"
  Muses from my development journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aurda012
learn_profile: aurda012
email_username: alfredo.i.urdaneta@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
